name: Homes
version: 1.3
api-version: 1.19
main: net.vertrauterdavid.homes.Homes
author: VertrauterDavid
website: https://vertrauterdavid.net/ & https://github.com/vertrauterdavid/

commands:
  homes:
  home: